name: Get release version
on: 
  workflow_dispatch:
  release:
    types:
    - published
jobs:
  print_latest_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: |
          echo ${{github.event.release.tag_name}}
