name: Publish to Nuget
on:
  release:
    types:
      - published
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{github.workspace}}/nuget
defaults:
  run:
    shell: pwsh
jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Set version
        id: set_version
        shell: pwsh
        run: |
          echo "$version"
          $version = "${{github.event.release.tag_name}}"
          $isPrerelease = "${{github.event.release.prerelease}}" -eq "true"
          $hasPrereleaseSuffix = $version -match "-\w+"
          if ($isPrerelease -and -not $hasPrereleaseSuffix) {
            Write-Error "Pre-release tag must contain a suffix (e.g., -alpha, -beta, -rc). Found: $version"
            exit 1
          }
          
          if (-not $isPrerelease -and $hasPrereleaseSuffix) {
            Write-Error "Regular release tag must not contain a pre-release suffix. Found: $version"
            exit 1
          }
          echo "VERSION=$version" >> $env:GITHUB_ENV
      - run: dotnet pack --configuration Release --output ${{env.NuGetDirectory}} -p:PackageVersion=${{env.VERSION}}
      - uses: actions/upload-artifact@v3
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{env.NuGetDirectory}}/*.nupkg