name: Pack and Test
on:
  push:
    branches:
      - master
      - main
  pull_request_target:
    types:
      - opened
      - synchronize
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{github.workspace}}/nuget
defaults:
  run:
    shell: pwsh
jobs:
  pack_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Pack
        run: dotnet pack --configuration Release --output ${{env.NuGetDirectory}}
      - name: Run tests
        run: dotnet test --configuration Release
