name: Pack and test
on:
  push:
    branches:
      - main
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{github.workspace}}/nuget
defaults:
  run:
    shell: pwsh
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet pack --configuration Release --output ${{env.NuGetDirectory}}
      